### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by ds-codemag** [Cockpit-HQ/Cockpit#101]
For example when I'm trying to delete something or go to api playground I'm getting error 'crypto.randomUUID is not a function'.

I found answer that 'crypto.randomUUID function was added for Node versions > v14.17.0'

My server has not support for nodejs it is php only.

I ran 2.3.9 version where randomUUID function was not used and everything works fine. 

Is any possibility tu use latest version on my server?

**Comment by aheinze** [comment]
Why node!? Which Browser do you use? `crypto.randomUUID` is used on the client side.

See the browser list where `crypto.randomUUID` is supported:

https://caniuse.com/mdn-api_crypto_randomuuid
