### ISSUE TITLE
BUG: SVG upload

### ISSUE THREAD

**Issue by Esylias** [Cockpit-HQ/Cockpit#102]
svg files will be modified by uploader: informations will be dropped

**_original content_**

`<defs><filter id="Adobe_OpacityMaskFilter" filterUnits="userSpaceOnUse" x="17" y="13.1" width="23.6" height="14.7"><feColorMatrix  type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 1 0"/></filter></defs>`

**_uploaded content_**

`<defs><filter id="Adobe_OpacityMaskFilter" filterUnits="userSpaceOnUse" x="17" y="13.1" width="23.6" height="14.7"></filter></defs>`

filter informations are dropped and svg is broken

**Comment by aheinze** [comment]
Hi 👋 Can you you provide an example svg file? Thanks!
