### ISSUE TITLE
please revert collapsing permissions overview on roles page

### ISSUE THREAD

**Issue by raffaelj** [Cockpit-HQ/Cockpit#106]
I had to scroll in the old view, but I was able to spot all active permissions very fast. Now I have to click many times to see, which permissions were set. This is annoying and it's easy to miss some permissions.

Also expanding the cards is not possible with keyboard navigation.

**Comment by aheinze** [comment]
addressed here: https://github.com/Cockpit-HQ/Cockpit/commit/c0c01d937bbb42a2dd70b5a2851188522be4e517
