### ISSUE TITLE
`NS_BINDING_ABORTED` warning in browser network tab for assets thumbnail redirects

### ISSUE THREAD

**Issue by raffaelj** [Cockpit-HQ/Cockpit#110]
I'm not sure, if this is a problem or if it just looks ugly when inspecting requests of cockpit in the browser network.

Steps to reproduce:

* Use Firefox, open dev tools and look at "Network" tab
* Open assets page (with at least one asset) --> `302 --> 200`
* Reload page (press F5) --> `302 --> Blocked/NS_BINDING_ABORTED`

The images are displayed correctly, but the redirect from the thumbs url to the generated thumbs file is skipped internally.

**Comment by aheinze** [comment]
This is a firefox specific issue, that gets triggered when a connection gets aborted (to my research). As it is not critical and other topics have a higher prio I'll leave it for now
