### ISSUE TITLE
Cluster deployment /  user sessions in DB

### ISSUE THREAD

**Issue by corradofiore** [Cockpit-HQ/Cockpit#113]
Howdy,

I would like to install Cockpit on a cluster of 3 web servers with a common MongoDB backend.

From what I understand, session management in Cockpit is based on the native PHP mechanism, i.e. sessions are stored as files on the local file system.  This makes cluster deployment hard because you have to resort to sticky sessions on the load balancer and you will lose a % of sessions if one of the machines is unavailable (thus negating the benefit of a cluster deployment).

Is there a way to store sessions on MongoDB instead?

**Comment by aheinze** [comment]
Hi 👋

For cluster deployments I recommend to use redis as session storage.
You need then to update the php ini to to use redis as the session handler:

https://github.com/phpredis/phpredis#php-session-handler

**Comment by corradofiore** [comment]
Awesome, thank you so much!
