### ISSUE TITLE
Add "Preview page" Button

### ISSUE THREAD

**Issue by joelsinnott** [Cockpit-HQ/Cockpit#117]
This would be a great quality of life addition :) So I dont have to scramble to find the correct preview link every time.

**Comment by aheinze** [comment]
The functionality is already there, just needs to be implemented in you project

**Comment by mountainash** [comment]
Could you please add to the [Documentation](https://getcockpit.com/documentation/core/quickstart/configuration) on how to setup the Preview feature... both within Cockpit, and how your server should support it? (is there any queries sent from it)?
