### ISSUE TITLE
labels of boolean fields not clickable in field settings modal

### ISSUE THREAD

**Issue by raffaelj** [Cockpit-HQ/Cockpit#125]
When editing a model and opening the field settings modal, the boolean field labels aren't clickable.

See also #108

**Comment by aheinze** [comment]
Can't verify the described behaviour:


https://github.com/Cockpit-HQ/Cockpit/assets/321047/69d7a93b-08b2-4ea7-b310-d03e8415775e

**Comment by raffaelj** [comment]
> Can't verify the described behaviour

Me neither. I used an outdated version (probably 2.5.2) in a test folder when I wrote this issue.
