### ISSUE TITLE
`function Cockpit()` in async script seems unnecessary

### ISSUE THREAD

**Issue by raffaelj** [Cockpit-HQ/Cockpit#145]
I don't understand, why the async worker needs an extra function `Cockpit()`.

See: https://github.com/Cockpit-HQ/Cockpit/blob/develop/modules/App/Helper/Async.php#L58C1-L68C2

```php
function Cockpit() {

    static \$instance;

    if (!isset(\$instance)) {
        \$instance = Cockpit::instance('{$envDir}');
        \$GLOBALS['APP'] = \$instance;
    }

    return \$instance;
}
```

The same effect can be achieved with

```php
// current behavior
//\$app = Cockpit::instance('{$envDir}');

// with fix from #144
\$app = Cockpit::instance('{$envDir}', ".\var_export($this->app['initialConfig'], true).");
```

in `modules/App/Helper/Async.php` and a small replacement of `Cockpit()` with `$app` in

* https://github.com/Cockpit-HQ/Cockpit/blob/develop/modules/Content/bootstrap.php#L520
* https://github.com/Cockpit-HQ/Cockpit/blob/develop/modules/Content/bootstrap.php#L530

**Comment by aheinze** [comment]
Hi 👋 

With `Cockpit()` I don't have to care about the current environment/Space when writing async code. It will always return the contextual right instance.

**Comment by raffaelj** [comment]
Do you think about multi-threaded code? If so, I didn't dig deep enough, to understand how scoping and object sharing works.

If not, I don't see any advantage. With each (async) call a new thread starst, a new instance is created and all information to start that instance with the right config for spaces is already present in the created file.

Do you have an example, where the function `Cockpit()` is useful?
