### ISSUE TITLE
Default login creds for cockpit

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [Cockpit-HQ/Cockpit#150]
Hello @maintainer

What is the default password and username for cockpit login (docker installation)?

**Comment by AkshayraviC09YC47** [comment]
<img width="1426" alt="image" src="https://github.com/Cockpit-HQ/Cockpit/assets/58636452/98a2ac2f-e6d7-40c6-8aa0-501a44616fb5">

BTW: Getting error with admin:admin

**Comment by aheinze** [comment]
run `/install` first

**Comment by AkshayraviC09YC47** [comment]
Thanks :)

**Comment by AkshayraviC09YC47** [comment]
Hello @aheinze 

i have reported one security issue via hunt.dev, pls check this

https://huntr.dev/bounties/e4e6b3d3-565f-440f-bc56-5f09b9057617

**Comment by AkshayraviC09YC47** [comment]
Hello @aheinze 

Reported one more issue and my opinion is to implement a solution for this rather than the above one, pls look into this

https://huntr.dev/bounties/3179963a-cd1b-4a0e-a8c6-82d65d9ac109

If you decide to address this matter, I recommend using the same commit SHA to close both tickets.
