### ISSUE TITLE
Navigating to next asset within Edit asset modal

### ISSUE THREAD

**Issue by m00gendai** [Cockpit-HQ/Cockpit#154]
Current workflow when adding descriptions to assets:

- Click three dots of asset
- Select "Edit"
- Enter description
- Update
- Close Edit asset modal
- Click three dots of next asset
- ...

Expected workflow:

- Click asset (see also #51)
- Enter description
- Update
- Click "next asset" or similar navigation which loads the next (or previous) asset in the current folder
- Enter description
- ...

**Comment by aheinze** [comment]
You don't need to click on the dots. Just click on the assets title 🤷‍♂️

**Comment by m00gendai** [comment]
This doesn't answer the issue of not being able to navigate to the next/previous asset within the Edit modal, though.
