### ISSUE TITLE
Is Gallery field type coming back?

### ISSUE THREAD

**Issue by kvanska** [Cockpit-HQ/Cockpit#155]
Or is there a way to make a workaround with the current version?

**Comment by ebrenner-code** [comment]
My guess is there was a choice made to move everything to the asset field for simplicity and I like this change, but we desperately need a way to add many assets at once. The grid layout that the gallery field used would also be a welcome return.

**Comment by aheinze** [comment]
See my response here: https://discourse.getcockpit.com/t/multi-select-photos-assets/2871/4
