### ISSUE TITLE
Asset title not displayed on mutiselect asset input

### ISSUE THREAD

**Issue by Mikearaya** [Cockpit-HQ/Cockpit#157]
currently: Empty

![Screenshot from 2023-09-15 17-33-12](https://github.com/Cockpit-HQ/Cockpit/assets/9751246/b552c1f9-3ebe-4794-99f1-c3039e9ff556)

Expected: some what to select what to display or display the a default value like the asset title

**Comment by aheinze** [comment]
Can you update to v2.7.0:

![image](https://github.com/Cockpit-HQ/Cockpit/assets/321047/718a937e-4a0e-47ef-a70f-b5a3c3aeff9f)

**Comment by Mikearaya** [comment]
Thanks, its fixed now
