### ISSUE TITLE
How to extend WYSIWYG editor  tinymce config

### ISSUE THREAD

**Issue by Mikearaya** [Cockpit-HQ/Cockpit#158]
I wanted to enable the toolbar and also  font-changing
how can i extend the default text editor appearance configuration
https://www.tiny.cloud/docs-4x/configure/editor-appearance/

**Comment by Mikearaya** [comment]
Found the solution but it would be helpful if is included on the documentation page. but until then if anyone is curious this is a good starting point https://discourse.getcockpit.com/t/customize-wysiwyg/2466/2?u=mikearaya

**Comment by aheinze** [comment]
It is: https://getcockpit.com/documentation/core/concepts/fields#wysiwyg
