### ISSUE TITLE
How do I change the default dashboard language ?

### ISSUE THREAD

**Issue by mr-cozay** [Cockpit-HQ/Cockpit#16]
Hi, I am new to this cms. I want to change the default dashboard language. Is there a configuration file for this? Is this possible from the dashboard?
Finally, how to do it correctly?

**Comment by raffaelj** [comment]
If you created users (or you are the default admin user), your user profile has the default app locale, which is "en". After changing i18n to "de" in your `config.php`, all new users get that locale by default.

1. Add `'i18n' => 'de'` to your `config/config.php`
2. (optional) Go to Settings --> Locales --> Add Locale; than create locale "fr"/"Francais
3. Edit your user profile `/system/users/user`; scroll to "Admin UI language" and change your locale from "en" to "de"
4. Run the cli command `php ./tower app:i18n:create ` to create empty language files in `config/i18n/{module}/{locale}.php`
5. Translate Cockpit

If you search for a German translation, I already started one, but didn't publish it, yet. Just let me know.

**Comment by mr-cozay** [comment]
I did it and it works. @raffaelj thank you very much!

**Comment by mr-cozay** [comment]
I did it and it works. @raffaelj thank you very much!

**Comment by mr-cozay** [comment]
I did it and it works. @raffaelj thank you very much!
