### ISSUE TITLE
select field: display value instead of label

### ISSUE THREAD

**Issue by falk-m** [Cockpit-HQ/Cockpit#165]
Hi,

i use the feature, that i can use objects instead ob simple strings to define a select list option:
![image](https://github.com/Cockpit-HQ/Cockpit/assets/121984937/70773364-15bf-4b24-881b-8299f3f7ee10)

the benefit is, that i use labels for the view and a value how is stored.
the select field support thi, so use can use as option a object with the properties: label, value and group.

It looks nice in the select box:
![image](https://github.com/Cockpit-HQ/Cockpit/assets/121984937/501be5ea-c1aa-440c-ac55-8da0cce4df6d)

The problem is that in die detail view it shows the stored value und not the label from the option
![image](https://github.com/Cockpit-HQ/Cockpit/assets/121984937/3fc7b64b-06a8-4300-bb49-766a4230ecbc)

api/modules/App/assets/vue-components/fields/field-select.js

```
render(value, field) {
            return Array.isArray(value) ? value.join(', ') : value;
        }
```

the solution is to select the label from the possible options:

```
render(value, field) {
            
            if (field.opts && field.opts.options && Array.isArray(field.opts.options)  && field.opts.options.length > 0 && (typeof(field.opts.options[0]) !== 'string')) {
                
                const selectedValues = typeof (value) === 'string' ? value.split(',') : value || []
                var selectedOptions = field.opts.options.filter((o) => selectedValues.indexOf((o.value ?? o).toString().trim()) !== -1);

                if(selectedOptions.length > 0){
                    return selectedOptions.map(o => (o.label ?? o).toString().trim()).join(", ");
                }
            }

            return Array.isArray(value) ? value.join(', ') : value;
        }
```

then it work nice.

![image](https://github.com/Cockpit-HQ/Cockpit/assets/121984937/622c4f13-2d20-474d-97b7-6efe6abd79d7)

i create i n few minitutes a pull request linked to this issue

**Comment by aheinze** [comment]
fix merged
