### ISSUE TITLE
Facing issue with PHP Version 8.1.12 

### ISSUE THREAD

**Issue by ysushah** [Cockpit-HQ/Cockpit#168]
Facing issue with PHP Version : 
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.12. in <path>lib\vendor\composer\platform_check.php on line 24

**Comment by aheinze** [comment]
Unfortunately the symfony/finder component requires PHP >= 8.2. You need to upgrade your PHP version to >= 8.2. Cockpit also already supports 8.3.
