### ISSUE TITLE
Preview Mode not working / Regression in 2.8.0/2.7.2

### ISSUE THREAD

**Issue by pozylon** [Cockpit-HQ/Cockpit#171]
In Cockpit >2.7.2 the preview mode is defunct.

It is because "fields-renderer.js" not found from the preview dialog module. Propably should be fields/renderer.js now

**Comment by pozylon** [comment]
@aheinze Fixed it locall by modifying dialogs/preview

**Comment by pozylon** [comment]
import fieldsRenderer from "../vue-components/fields-renderer.js"
->
import fieldsRenderer from "../vue-components/fields/renderer.js"

**Comment by aheinze** [comment]
Thank you for reporting! I'll release a fixed version this weekend.
