### ISSUE TITLE
Local test with XAMPP fails with 404: "Requested resource is not available" (after install)

### ISSUE THREAD

**Issue by Der-K-2000** [Cockpit-HQ/Cockpit#173]
I get a 404 error after a successful installation.

1. calling `/install` (with no issues)

![grafik](https://github.com/cockpit-project/cockpit/assets/7254827/1eb7ea59-5d0f-4ba3-a42b-644436e9f944)

2. Pushing the button `login now` will forward to `/` and it shows this:

![grafik](https://github.com/cockpit-project/cockpit/assets/7254827/d33d4c55-7218-4235-bcdb-1cddde85b36e)

***

- It's a fresh XAMPP installation (win)
- PHP v8.2.12 / Apache v2.4.58
- all required extensions are installed
- `mod_rewrite` is activated (php.ini)
- `AllowOverride All` (httpd.conf)
- all files are stored (also .htaccess)
- server/services restarted after file editing

***

This problem could be related to: https://github.com/agentejo/cockpit/issues/686

**Comment by aheinze** [comment]
Sorry, never tested it on a win environment. Maybe the apache error or php error logs might give some insights

**Comment by aheinze** [comment]
Maybe you should try out to run Cockpit with [docker](https://hub.docker.com/repository/docker/cockpithq/cockpit/general)
