### ISSUE TITLE
UX: Increase the click hit-area on sub folder navigation

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#175]
Currently (in the Assets) the directory navigation active link size is only as big as the name of the directory (small names are hard to hit), yet the button overall is quite large.

I suggest increasing the `A` to a block element and even include the icon to make it easy/faster to locate and click.

## Example

<img alt="Screenshot" src="https://github.com/Cockpit-HQ/Cockpit/assets/27637/00eecb95-d67a-4130-bfd4-e8254da818e3">
In the above screenshot the blue rectangle is the current link - I suggest expanding this to the red rectangle.

**Comment by mountainash** [comment]
I'm not sure on how the rest of the project is built - but this code change would not be good for accessibility (mainly screen readers)

**Comment by aheinze** [comment]
https://github.com/Cockpit-HQ/Cockpit/commit/2f9b9e027b6b269fa18b63a5e1c9d5372d7d050a

**Comment by aheinze** [comment]
accessibility is a huge topic, but I'm always thankful for hints 🙂
