### ISSUE TITLE
The height property for the code input type seems to need fixing

### ISSUE THREAD

**Issue by AnmSaiful** [Cockpit-HQ/Cockpit#176]
**For example, let's try with a value of `10` for the height property:**

<img width="862" alt="Screenshot 2024-02-18 at 17 15 41" src="https://github.com/Cockpit-HQ/Cockpit/assets/204376/d18a1527-eea0-42ef-9aef-33562a6d922e">

**And we get this during the item creation:**

<img width="757" alt="Screenshot 2024-02-18 at 17 16 18" src="https://github.com/Cockpit-HQ/Cockpit/assets/204376/2c18a978-fcef-4c1a-8c81-cc79790c7eec">

**If we remove the value (i.e., `10`) from the height property, the item creation screen renders as expected:**

<img width="757" alt="Screenshot 2024-02-18 at 17 17 08" src="https://github.com/Cockpit-HQ/Cockpit/assets/204376/0e6dd24c-19e0-4a04-a836-0319dd7fd98f">

Thanks for considering the fix in the next release. ;-)

**Comment by aheinze** [comment]
you've set the height to `10px` 😉

**Comment by AnmSaiful** [comment]
Ah! I see... since there was no indication of the unit, I thought it would be the number of rows.

I recommend mentioning the unit. 😊
