### ISSUE TITLE
[Feature] Technical ID for a page

### ISSUE THREAD

**Issue by pozylon** [Cockpit-HQ/Cockpit#180]
It would be awesome to have a technical id that can be set on a per-page base for developers, so I can fetch a certain page with an id like "forgot-password" or "home" and i don't have to take care of having slug's in sync.

Using the id of the page automatically set by cockpit comes with it's own issues, for example when I hardcode it in code and the page gets re-created.

**Comment by aheinze** [comment]
Can't you utilize the metada of a page for this?

![image](https://github.com/Cockpit-HQ/Cockpit/assets/321047/87b111ad-31d5-4eef-8780-086db7c00446)

And the use the pages api:

```
api/pages/pages?filter={"_meta.customId":"MyId"}&limit=1

```

**Comment by pozylon** [comment]
Oh wow i didn't know that hidden meta option of the pages, it only shows up when i filter explicitly for it. Cool, that's it.
