### ISSUE TITLE
How to use php mailer in cockpit ??

### ISSUE THREAD

**Issue by abdallahhelmy99** [Cockpit-HQ/Cockpit#181]
I am using cockpit as my cms for an ecommerce web app .. I want to send a couple of mails on different events like for example when an order entry is added to Orders collection a mail shall be sent .. I want this to be done inside a specific spaces. Any help please ? I already searched a lot for how to implement this.

**Comment by aheinze** [comment]
crete a `bootstrap.php` file in your targeted space config folder, eg `.spaces/myspace/config/bootstrap.php`

then add event listeners there:

```php
<?php

$app->on('content.item.save', function($modelName, $data) {...});
```
