### ISSUE TITLE
GraphQL Bug: Usage of "multiple" in a select leads to wrong schema

### ISSUE THREAD

**Issue by pozylon** [Cockpit-HQ/Cockpit#183]
Currently graphql always assumes String even if "multiple" is set to true, but in the db it's an array in those cases leading to a fatal error.

- Should be [[String!]!]! for multiple true and allowMultipleValues true
- Should be [String!]! for multiple true and allowMultipleValues false
- Should be [String!]! for multiple false and allowMultipleValues true
- Should be String for multiple false and allowMultipleValues false

**Comment by aheinze** [comment]
what is allowMultipleValues here? There is only multiple as a field setting

**Comment by pozylon** [comment]
1. tab
<img width="1813" alt="Bildschirmfoto 2024-05-08 um 10 01 18" src="https://github.com/Cockpit-HQ/Cockpit/assets/2109393/f39eaa80-1bba-4ec9-bb6f-35cb6988fc38">

2. tab
<img width="352" alt="Bildschirmfoto 2024-05-08 um 10 01 41" src="https://github.com/Cockpit-HQ/Cockpit/assets/2109393/87e40227-3ecd-413a-837b-3d1e7c37078f">

**Comment by aheinze** [comment]
Thanks! Should be fixed in the dev branch now
