### ISSUE TITLE
_cby and _mby are NULL by default?

### ISSUE THREAD

**Issue by ronaldaug** [Cockpit-HQ/Cockpit#186]
I'm not quite sure this is intentional or a bug.

When creating a new item using the user key `USR-1234567890` through REST API, the _cby and _mby fields are saved as `NULL`, instead of the user ID of who created that item.

## Steps to Reproduce
- Cloned the latest develop branch
- Created a new model
- Sent a POST request via REST API `/api/content/item/{model}`
- And create a new item using the `user key` under every user's profile
The response showed the following:

```json
{
    "title": "Test post",
    "description": "Test post description",
    "_state": 1,
    "_modified": 1714704858,
    "_mby": null,
    "_created": 1714704858,
    "_cby": null,
    "_id": "5bbd652d30666595f5000208"
}
```

## Expected Behavior
The `_mby` and `_cby` fields should contain the user ID of the user who created the item, not null.

**Comment by aheinze** [comment]
Thanks for reporting!
