### ISSUE TITLE
[Feature] Root slug

### ISSUE THREAD

**Issue by pozylon** [Cockpit-HQ/Cockpit#189]
Problem: When using the slugs in "Pages" of Cockpit Pro, we always have to define a "home" page and add workarounds in the frontend to map / to /home because it's currently not possible to have an empty slug or a root slug.

Suggestion: Have some checkbox next to slug field "root page" or equivalent solution that allows storing the page's slug as empty string.

**Comment by aheinze** [comment]
you can always query for the root page by `/api/pages/page?route=/`.

The root page is always the first page in the site tree
