### ISSUE TITLE
[Bug] Adding class to Section-layout-component doesn't save

### ISSUE THREAD

**Issue by DanielWahl** [Cockpit-HQ/Cockpit#190]
Version: Tested on Cockpit Pro 2.8.4 (fresh install) and 2.6.1 with mongolite, tested on different websites and installations.
System: Ubuntu 20, PHP 8.2.19, Node.js v18

There seems to be a bug with adding a class to a section layout component on a page.

When creating a new section on a page without a class, the class-attribute is sent as null, which works.

![Bildschirmfoto 2024-05-22 um 17 57 10](https://github.com/Cockpit-HQ/Cockpit/assets/9644563/a0bc47ee-fcce-46d5-a9bf-acd80de050f9)

But after adding a class (and also after removing the text after once adding one -> empty string instead of null), the request resolves in a `/pages/save 403 (Forbidden)` with `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'error')`.

**Comment by aheinze** [comment]
Hi 👋 Can't verify it. If you go to `Settings > Logs > Errors`, do you see a related error there? If yes, can you post here the details?

Thanks!

**Comment by DanielWahl** [comment]
It seems to be resolved now.
No idea why, maybe was a server problem and an update fixed it.

Thanks for your quick response.

**Comment by DanielWahl** [comment]
https://emo.cockpit.whale.lu/assets/link/377f56f5633965b91b0001c5

**Comment by DanielWahl** [comment]
It was somehow resolved and it works now.
Maybe it was a server problem and an update fixed it, but unsure.

There were no errors-logs for not saving.

Thanks for your quick response.
