### ISSUE TITLE
Option to extend page default fields

### ISSUE THREAD

**Issue by Mikearaya** [Cockpit-HQ/Cockpit#191]
Currently, a page whether it a layout, collection, or singleton has only a few default inputs 
- title
- slug
- SEO {}
-layout components []

is there a configuration to extend the default inputs either per page bases or globally that will enable us to add additional fields for example change it to:

- title
- **subtitle**
- slug
- SEO {}
-layout components []

**Comment by aheinze** [comment]
In your `config/bootsrap.php`:

```php
<?php

$app->on('pages.pagetype', function($types) {

    $data = $types['layout']['data'];

    $types['layout']['data'] = function() use ($data) {

        return array_merge([
            [
                'name' => 'subtitle',
                'type' => 'text',
            ]
        ], $data());
    };

});

```

**Comment by Mikearaya** [comment]
thanks
