### ISSUE TITLE
🐛 Asset preview doesn't show videos

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#192]
Fields [in a component] with Type=asset, don't show a preview when the selected asset is a video file.

This is inconsistent with how static image assets work - they load for previewing.

What's worse for the UX is that a "loading" indicator shows - it would be more honest to show a information label "Video preview unavailable" (or similar).

## Example showing a Video asset
<img width="393" alt="Screenshot 2024-06-05 at 09 37 02" src="https://github.com/Cockpit-HQ/Cockpit/assets/27637/d89702e9-3e2b-4202-ab96-1e0f14f0973c">
<img width="834" alt="Screenshot 2024-06-05 at 09 35 44" src="https://github.com/Cockpit-HQ/Cockpit/assets/27637/c9971ea8-01fa-4975-afec-009991cd2cc4">

## Example showing an Image asset
<img width="401" alt="Screenshot 2024-06-05 at 09 37 49" src="https://github.com/Cockpit-HQ/Cockpit/assets/27637/c4ea38e6-57c3-417e-a6c7-cc00f3311455">
<img width="824" alt="Screenshot 2024-06-05 at 09 37 32" src="https://github.com/Cockpit-HQ/Cockpit/assets/27637/a6d66f18-7b7c-49b7-9bb8-cabf1da3b4cb">

**Comment by aheinze** [comment]
Looks like a cors issue after switching to the new env domains. I'll look into the aws s3 settings
