### ISSUE TITLE
cannot edit fields in singleton or collection

### ISSUE THREAD

**Issue by pizerodev** [Cockpit-HQ/Cockpit#193]
<img width="1353" alt="image" src="https://github.com/Cockpit-HQ/Cockpit/assets/50109208/1c2257ea-cfca-4fc2-b37b-0c42abbf3dad">

Am I doing something wrong? I cannot see an option to add fields

**Comment by aheinze** [comment]
Hi! Sorry, can't verify the issue. Can you provide more details about used Browser, Os etc?

Also, can you post (if exists) the error you get in the console?

Thanks!
