### ISSUE TITLE
Migration from 0.12 to 2.2

### ISSUE THREAD

**Issue by Karol-Waliszewski** [Cockpit-HQ/Cockpit#20]
Is there a possibility to migrate my CMS from Cockpit version 0.12, to the new system on version 2.2? Did you provide any documentation to the problem?

**Comment by aheinze** [comment]
Migration consulting is provided by [Agentejo](https://agentejo.com/). Get in touch if you need support

**Comment by lichtteil** [comment]
@Karol-Waliszewski did you find an easy solution? It's really a bummer that there is word about that anywhere.
