### ISSUE TITLE
Extract bootstrapping tasks from index.php

### ISSUE THREAD

**Issue by Tiefseetauchner** [Cockpit-HQ/Cockpit#204]
Hey!

I'm working on yet another addon, this time to make a sitemap, and my idea was to have a sitemap.php that one can just include from the outside. For that I want to use cockpit functionality and the best idea I had was to include the code from index.php. Would it make sense to extract the setup of the app component into another file so one can easily include it externally? Imho index.php shouldn't do too much itself regardless, but I can see that it might get convoluted to have index.php -> setup.php -> bootstrap.php

If there's a better way to get the $app from an external (kinda) script I'm happy too.

Best, Lena

**Comment by aheinze** [comment]
Hi 👋

Which functionality do you need exactly?

All you have to do is to include `{path_to_cockpit}/bootstrap.php`.

Then just init the Cockpit app:

```php
<?php

include('{path_to_cockpit}/bootstrap.php');

$cockpit = Cockpit::instance();

```

That's it ☝️

**Comment by Tiefseetauchner** [comment]
Thank you! I've been using the $app instance from index.php, I didn't realize you could instantiate Cockpit without parameters...
