### ISSUE TITLE
UI: Sort Env (Environment Variables)

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#205]
I'm not sure what order the EnvVar list under the Admin > System settings are, but alphabetical would be much easier to read - esp. when you have many prefixed with the same word and they are near/next to each other in the list.

Like in this case `COCKPIT_` vars are not ordered.

<img width="192" alt="Screenshot 2024-08-09 at 16 29 47" src="https://github.com/user-attachments/assets/071281c5-499d-484f-9fd1-f3bb05da456a">

**Comment by aheinze** [comment]
Thanks! Fixed here: https://github.com/Cockpit-HQ/Cockpit/commit/049bcfa2d70697f05bb7d5f5efc6b63ff33ce559
