### ISSUE TITLE
[BUG] UL: error 500 layout

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#207]
<img width="616" alt="Screenshot 2024-08-15 at 09 50 53" src="https://github.com/user-attachments/assets/e2fcf39b-895c-4403-8b61-60f6d8bd85f5">

Could be prettier 💅🏼 

Can trigger if on the Webhooks page and then you change the key in the URL.

It should also probably technically be an Error 404, not 500.

**Comment by aheinze** [comment]
Fix will be available in the next version 👍 Thanks for reporting!
