### ISSUE TITLE
[UI] "Api", "API", "api"

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#209]
> Consistency is the sign of good design
-- someone once said (I'm sure)

Cockpit should standardise on one way to write the acronym "API" (IMO in CAPITAL LETTERS/UPPER CASE)

<img width="703" alt="Screenshot 2024-08-19 at 14 32 50" src="https://github.com/user-attachments/assets/0a39e750-45ed-4e34-bcd3-c8b9ae3d3d24">

**Comment by aheinze** [comment]
Thanks for the hint!

**Comment by mountainash** [comment]
Does the fix within the "Rest-Api Viewer" too?
<img width="381" alt="Screenshot 2024-08-20 at 13 39 31" src="https://github.com/user-attachments/assets/b36dacb7-31a7-46af-aef9-c1c93df2abc6">
