### ISSUE TITLE
Assets more triggers - feature request

### ISSUE THREAD

**Issue by Frou-HOS** [Cockpit-HQ/Cockpit#21]
Is it possible to have a trigger after the asset was inserted in dataStorage ?

Actually in the ‘add’ function of module Assets the trigger ‘assets.add’ is trigged before the insert in datastorage

```
$this->app->trigger('assets.add', [&$assets]);
$this->app->dataStorage->insert('assets', $assets);
```
And if i want to make some modifications on the asset after the upload/add action it’s not possible.
Maybe for the trigger assets.asset.update is necessary too !?

Some thing like that : 

- $this->app->trigger('assets.add.done', [&$assets]);
- $this->app->trigger('assets.asset.update.done', [&$assets]);

**Comment by aheinze** [comment]
can you provide a specific case where an event is useful after saving an asset?
