### ISSUE TITLE
[UI]: Disable Page Translation

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#211]
Cockpit has the ability to disable the translation of a page, which is a nice feature as not every page needs to be written in every language; but the UI to knowing this is very cryptic. Can I suggest that when hovering over the green 🟢 or red 🔴, there's a tool-tip/`title` that tells the user what it does (and what state it's in - for accessibility [not everyone sees red and green])

<img width="291" alt="Screenshot 2024-08-21 at 16 39 32" src="https://github.com/user-attachments/assets/15e755da-c23f-4d1e-b712-e1514fc515e8">

**Comment by aheinze** [comment]
Good point 👍

**Comment by aheinze** [comment]
tooltips are available in the current dev version. Thanks!

**Comment by mountainash** [comment]
Nice! Way to go!

- [ ] One related UX tip... currently each language "eye" acts to show/hide all the components for that translation... some time you want an easy way to disable them all and just see one language (like a swap). It would be useful if there was a "show/hide all" option. This is very helpful when there's a lot of translations. /cc @aheinze
