### ISSUE TITLE
[UX]: Global search to include routes/paths

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#212]
The Global Search bar is really helpful for quickly finding content and humping to it (esp. on large sites where getting to a deep child in pages would require many many clicks).

It seems to have the "content" of pages indexed, but could it also please index the slug/route/path (and parts of it) to allow lookup of content based on use of terms in the URL?

<img width="257" alt="Screenshot 2024-08-21 at 17 06 45" src="https://github.com/user-attachments/assets/116ba203-aee4-4964-9adc-20a4266289b8">

**Comment by aheinze** [comment]
Will be available in the next release (results for titles + slugs) 👍
