### ISSUE TITLE
[BUG]: acronym "JSON" not "Json"

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#213]
<img width="331" alt="Screenshot 2024-08-24 at 11 26 23" src="https://github.com/user-attachments/assets/844f3851-15ff-48db-8f50-db3d4bc8dde8">

- [ ] modal on a Collection
- [ ] UI: also the focus state in darkmode has accessibility issues

**Comment by mountainash** [comment]
That was a fast fix!

Do you need to update any translation files?

What about the dark ode issue too?

**Comment by aheinze** [comment]
All done 👍 Thanks!
