### ISSUE TITLE
[FEATURE]: `type` filter for API request /pages/routes

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#215]
It would be nice to limit the `/api/pages/routes` endpoint to filter by include (only) or exclude the returned results by a set-able type query.

**Comment by aheinze** [comment]
What is a possible use case here?

**Comment by mountainash** [comment]
When you need to build different routes for non-content pages (which are generally handled by a runtime "catchall" route).

**Comment by aheinze** [comment]
Will be available in the next release 👍
