### ISSUE TITLE
PHP warning of access array offset on null in License helper

### ISSUE THREAD

**Issue by pshemek** [Cockpit-HQ/Cockpit#218]
`Trying to access array offset on null in /public_html/modules/System/Helper/License.php on line 87`

```
public function isProprietary() {
        return (json_decode(file_get_contents(APP_DIR.'/composer.json'), true)['license'] === 'proprietary');
}
```

**Comment by aheinze** [comment]
Do you have the composer.json file missing?

**Comment by pshemek** [comment]
It turned out that I had the composer.json file formatted incorrectly. Thanks for the direction.
