### ISSUE TITLE
404 Error "Requested resource is not available" after successful CMS installation

### ISSUE THREAD

**Issue by desvu** [Cockpit-HQ/Cockpit#219]
I have successfully installed the latest version of Cockpit CMS. However, when trying to access the admin panel, I get a 404 error "Requested resource is not available".

The site is hosted in the following directory: C:\xamppserver\htdocs\testcockpit\cockpit-core

Request to http://localhost/testcockpit/cockpit-core/install/ - successful CMS installation
Request to http://localhost/testcockpit/cockpit-core - 404 error

PHP GD - Enabled 
XAMPP Control Panel v3.3.0 (All settings are default, only the GD extension is enabled)
Windows 10 Pro x64

**Comment by aheinze** [comment]
Hi! Sorry, but Cockpit is not tested on windows or xampp. Maybe you can try to run a webserver via wsl on windows?

**Comment by desvu** [comment]
> Hi! Sorry, but Cockpit is not tested on windows or xampp. Maybe you can try to run a webserver via wsl on windows?

Thank you, but I don't have the possibility. I’ve never had any issues with Cockpit CMS before. The old version (0.12.2) works perfectly on XAMPP. The new version doesn't work anywhere, be it WAMP, XAMPP, or OpenServer with Nginx.

**Comment by aheinze** [comment]
You should look into running your local webserver via wsl or docker (eg ddev)
