### ISSUE TITLE
UI: Sync Log

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#220]
When doing a Sync between Cockpit instances from the Setting section - there's a helpful log to show the progress... but as soon as the Sync finishes the log disappears.

It would be nice if the log stayed on screen until the user/Admin dismisses it - it's very helpful to be able to see what happened (after it's happened).

- [x] keep the Log on the screen until the user dismisses it.

**Comment by aheinze** [comment]
Will be available in > v2.9.2 👍
