### ISSUE TITLE
Production setup/debug mode

### ISSUE THREAD

**Issue by matej-bittner** [Cockpit-HQ/Cockpit#221]
Hi, I've been trying all day to set Cockpit to production mode, but nothing seems to be working. Even though I set 'debug' => false in config/config.php and Cockpit shows 'Debug mode Disabled,' it doesn't seem to have any effect. According to the documentation I found, this should be enough to lock model creation and similar features. Can someone explain how it actually works?

**Comment by aheinze** [comment]
What do you expect from "production mode"!?
