### ISSUE TITLE
[UX]: Lokalize hides long keys

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#224]
It's common on large sites to make some type of prefixes to sort translation keys... the current Cockpit UI makes this not so easy to use.

Suggestions
1) allow the table to use more of the whitespace on either side of the table on large screens
2) add a `title=` attribute to the HTML to allow for a tooltip/label showing the full key name on hover.

<img width="1047" alt="Screenshot 2024-10-01 at 18 45 18" src="https://github.com/user-attachments/assets/e3688088-51e2-4563-b500-bd5e48e889b8">

**Comment by aheinze** [comment]
I've added a title attribute 👍 Thanks for the hint!

**Comment by mountainash** [comment]
Title attribute is the slower option for UX as you have to wait each time on each string. There's a lot of white space that could be used. Even better would be to allow the column sizes to be adjusted.

**Comment by aheinze** [comment]
the column is also wider now ☝️
