### ISSUE TITLE
The endpoint /assets/thumbnail/T always produce 500 Internal Server Error

### ISSUE THREAD

**Issue by Pa55er6y** [Cockpit-HQ/Cockpit#228]
An authenticated user is needed to trigger this issue. 

The endpoint `/assets/thumbnail/T` would always respond with `500 internal server error`, using at least GET/POST/PUT methods, with or without a JSON request payload. The server only responds with `{"error": "500", "message": "system error"}` without detailed information. 

It seems that this endpoint comes with a fresh installation of CockpitCMS. To reproduce, make a fresh installation of Cockpit, login, and then try to access `http://{IP_address}/assets/thumbnail/T`. It should display a 500 server error. 

Version: 2.9.4
OS: Ubuntu 24.04
Setup: PHP 8.3.6 + SQLite

**Comment by aheinze** [comment]
Thanks for reporting!
