### ISSUE TITLE
Lokalize and permission issues

### ISSUE THREAD

**Issue by bomas13** [Cockpit-HQ/Cockpit#230]
I noticed that it is possible to query the API endpoint for Lokalize (`GET api/lokalize/project/{project}`) even w/o any "api-key" header supplied. However, providing a wrong token ends up in an "authentication failed" which matches my expectations.

This does not make any sense.

Likewise, previously it was possible to obtain tokens exclusively access to specific projects. This feature is gone completely. Will this be implemented in the future again? And if so, when?

**Comment by aheinze** [comment]
The fix will be available in the next release 👍 Thanks for reporting!
