### ISSUE TITLE
[UI] Sync selection not obvious

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#233]
In the Settings > Sync, when there's only one target to sync to, the modal that shows when you need to select the remote, it's not obvious that it's not initially selected (the radio button representation, looks like it's selected - but it isn't).

1. Make the pseudo radio button have obvious state
2. If there's only 1 remote it could be pre-selected (there's nothing else it could be)
 - (likewise) if there's only one direction, it could also be selected by default

**Comment by aheinze** [comment]
This will be fixed/available in the next release 👍 Thanks for the suggestion!
