### ISSUE TITLE
[FEATURE] Additional sync settings

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#235]
In the Setting up of a remote to sync to, it would be nice to also have a per server setting to default the following option:

- [ ] "always mirror" - to always make sure the remote has a perfect copy of the content from the source server

In addition it would also be helpful to have the ability to sync the following "security" settings:

- [ ] sync user accounts (with an obvious warning on why this might be bad) - but really helpful for a "backup" or co-lo load handler/fall-over server arrangement
- [x] sync roles and API endpoint permissions

**Comment by aheinze** [comment]
Syncing roles is available in the latest release. Syncing accounts open ups too many possible security issues.
