### ISSUE TITLE
Collection slug 

### ISSUE THREAD

**Issue by lukrate** [Cockpit-HQ/Cockpit#26]
**Version Pro**

Currently, the option in "pages" that allows to add a slug/routes to the item collections make a copy of the field. 

For example, the title "It's a beautiful day". 

It would be great if the field would be converted to a "browser-readable" address like: "its-a-beautiful-day".

___

**UPDATE**:

**Cockpit PRO v 2.3.0**

When a page is created the generated slug is correctly formatted to be "browser-readable".

![image](https://user-images.githubusercontent.com/6481999/190631470-e5b0dfaa-c783-47b0-9a8e-73dd8e05a592.png)

But when we set up the id of the collection which is the reference to create the route to the collection objects.

![image](https://user-images.githubusercontent.com/6481999/190632202-401ea68c-8ac7-4821-8ec2-8ae5f692af32.png)

The route to the collection object is not reformatted to be "browser-readable" like the page slug is.

![image](https://user-images.githubusercontent.com/6481999/190632709-61187a18-08e6-43e3-a671-45f61e76f918.png)

It would be really ideal if this could be improved.

Best regards

**Comment by aheinze** [comment]
Sorry, I don't get your issue. can you provide a more detailed description? Thanks!

**Comment by lukrate** [comment]
Updated

**Comment by aheinze** [comment]
You have to add a dedicated slug field to your collection.
