### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by goldenfaeron** [Cockpit-HQ/Cockpit#29]
Version: Cockpit Core

After installation, I got redirected to /auth/login?to=/. For me this was a blank page and the tab bar said: "Access denied!".
PHP 8.0 error was:
![WhatsApp Image 2022-09-24 at 19 06 23](https://user-images.githubusercontent.com/44201987/192110436-b80376c1-6143-470b-b446-d776d199d38d.jpeg)

I fixed it myself by casting the return value in Line 57 (/lib/Lime/Helper/Utils.php) to int
![image](https://user-images.githubusercontent.com/44201987/192110542-d89845ae-53f0-4900-b1fd-9114655025d7.png)

I am not a PHP pro, so I don't know if I damaged anything. I don't hope so.

Best Regards Tobias

**Comment by aheinze** [comment]
what is set for `post_max_size` and `upload_max_filesize` in your php.ini?

**Comment by goldenfaeron** [comment]
It's 32M, but this is not the point. I am running this on a **32 bit** Synology NAS and an Integer is between -2147483648 and 2147483647 on 32 bit. For 32M the result is 34359738368 which is too big. For now, I will just set `$max_size` to 0 or lower `post_max_size` and `upload_max_filesize`. Would it be possible to use floats instead of integers?

**Comment by aheinze** [comment]
Thanks for the hint. `round` returns always a `float`. Should be fixed now

**Comment by goldenfaeron** [comment]
Thanks allot! (Thank you for this super nice CMS btw)
