### ISSUE TITLE
Switch Model View

### ISSUE THREAD

**Issue by boehlim377** [Cockpit-HQ/Cockpit#30]
If you click on the expand icon in the Content / Collections area, an empty white window appears with the message [object HTMLElement]

**Comment by aheinze** [comment]
Sorry, can you describe it more detailed or provide a screenshot / screenrecording? Thanks!

**Comment by boehlim377** [comment]
If you click on this symbol
![symbol](https://user-images.githubusercontent.com/67892621/194840793-b7ad4191-df43-476c-8266-56559908a4c5.JPG)

... that appears:
![whiteWIndow](https://user-images.githubusercontent.com/67892621/194841035-4d510f12-3dec-48d4-bf43-ee0d1fd47c74.png)

**Comment by aheinze** [comment]
I can't confirm the issue. Do you see any js errors in the console? Which browser and os do you use?

**Comment by boehlim377** [comment]
Oh, sorry. It's actually a browser problem. It doesn't work under "Firefox 102.3.0esr", but it works under Chrome.

The console says: Switched to javascript:VueView.ui.offcanvas('content:assets/dialogs/switch-model-view.js')
