### ISSUE TITLE
Error in GET requests

### ISSUE THREAD

**Issue by unitedmonks-chandan** [Cockpit-HQ/Cockpit#32]
I am trying Cockpit for the first time today. Having errors in getting items but deleting items is working fine.

{"error":"SQLSTATE[HY000]: General error: 1 table `collections_team` already exists","file":"E:\\xampp\\htdocs\\cockpit\\lib\\MongoLite\\Database.php","line":153}

![image](https://user-images.githubusercontent.com/94685726/196171580-612adeee-64e6-4e9f-a0a4-d15cc3c709f5.png)

**Comment by aheinze** [comment]
Can you provide more information about your setup?

eg:

- OS
- Cockpit version
- PHP version

Looks like you're using Windows. Cockpit was never tested on Windows. Is there a chance that you you can test Cockpit on a linux or apple mac based system?

**Comment by unitedmonks-chandan** [comment]
@aheinze  You are right, the issue is on windows. I have just checked on Linux and it's working fine.

thanks for the response.
