### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by FMG-ITCommercial** [Cockpit-HQ/Cockpit#33]
Is it planned to provide a Docker Container in the future?
It was already asked in the Forum without answer :(
 https://discourse.getcockpit.com/t/dockerhub-image-for-v2/2451

**Comment by mandrasch** [comment]
Hey, saw this by accident while informing myself about cockpit cms!
Would also be cool if there would be a quick tutorial to run cockpit on [DDEV](https://ddev.readthedocs.io/en/stable/)
Much success with cockpit! 👍

**Comment by aheinze** [comment]
Initial docker images to play around with: https://hub.docker.com/repository/docker/cockpithq/cockpit

**Comment by FMG-ITCommercial** [comment]
THX for the quick solution

**Comment by Sonorpearl** [comment]
Thanks for the docker images. What paths should be a volume to have consistent data? Just `/var/www/html/storage`?

**Comment by aheinze** [comment]
> Thanks for the docker images. What paths should be a volume to have consistent data? Just `/var/www/html/storage`?

`/var/www/html/storage` and `/var/www/html/.spaces` (if you use spaces)
