### ISSUE TITLE
How to get unpublished collection items?

### ISSUE THREAD

**Issue by adiba** [Cockpit-HQ/Cockpit#34]
In the API playground below the response text field `GET /content/items/{model}`, the description "Get list of published model items" made me realize that this list is pre-filtered.

How can I get the *entire unfiltered list*, i.e., including unpublished items (i.e., items with `_state=0`)?

Even with `filter={_state:0}`, the result list didn't change (still only published items).

**Comment by aheinze** [comment]
Hey 👋

You have to create a custom api endpoint to allow `_state` filtering.

**Comment by Sonorpearl** [comment]
How would one add a custom API for that?

**Comment by aheinze** [comment]
Have a look here https://github.com/witsec/cockpit-api
