### ISSUE TITLE
Custom field types

### ISSUE THREAD

**Issue by FMG-ITCommercial** [Cockpit-HQ/Cockpit#35]
In the "old version" of Cockpit custom field types where possible when you install them via /config/tags.
Is that also possible with the new version?

**Comment by aheinze** [comment]
Hey 👋

This is not possible. But you can create a custom to re-create that functionality.

**Comment by FMG-ITCommercial** [comment]
Hey @aheinze where can we find a documentation for that? Couldn't find something in https://getcockpit.com/documentation/core/concepts/field-types
