### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by unitedmonks-chandan** [Cockpit-HQ/Cockpit#36]
Getting a proper response in Postman but cors error in the browser. any help?

Access to fetch at 'http://localhost/emergent/cockpit/api/content/items/Team' from origin 'http://localhost:2323' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
data.js:6          GET http://localhost/emergent/cockpit/api/content/items/Team net::ERR_FAILED
fetch_team @ data.js:6
(anonymous) @ data.js:16
(anonymous) @ data.js:17
data.js:6                  Uncaught (in promise) TypeError: Failed to fetch
    at fetch_team (data.js:6:30)
    at data.js:16:5
    at data.js:17:3

**Comment by unitedmonks-chandan** [comment]
Solved

**Comment by unitedmonks-chandan** [comment]
solved

**Comment by aheinze** [comment]
@unitedmonks-chandan could you share the solution. Would be helpful for others with the same problem. Thanks!
