### ISSUE TITLE
avif error - Could not encode image: No codec available

### ISSUE THREAD

**Issue by aiamk** [Cockpit-HQ/Cockpit#37]
i am getting error on thumbnail creation,

i am not sure from where i should get the codec, GD is installed.

`[29-Oct-2022 15:19:09 UTC] PHP Warning:  imageavif(): avif error - Could not encode image: No codec available
 in /shared/httpd/test/htdocs/cockpit-develop/lib/SimpleImageLib.php on line 182`

i am using devilbox docker php 8.1

Best Regards.

**Comment by aheinze** [comment]
The vendor SimpleImage lib doesn't support avif yet. 😔
