### ISSUE TITLE
Custom filters in collection list

### ISSUE THREAD

**Issue by thinkink** [Cockpit-HQ/Cockpit#38]
![image](https://user-images.githubusercontent.com/3516168/199272061-8aa9981a-41df-46dc-9328-6d1f82a4f25b.png)
what is the best way to add custom filter in collection list.

**Comment by thinkink** [comment]
I try to find more information about this. 
It's possible make custom views in pro addons (pages)

@aheinze if you can make a private meeting or more infomation about PRO 
thanks

**Comment by aheinze** [comment]
Hey 👋 custom views are not available yet but is already considered as a feature for a future release
