### ISSUE TITLE
No icons available

### ISSUE THREAD

**Issue by McGonigleStudio** [Cockpit-HQ/Cockpit#39]
I'm unable to change the Model icons. 

When I go to: 'Collection > Other > Icon'  it shows "No icons found"

![image](https://user-images.githubusercontent.com/52199309/199548449-611fabf0-8d99-4155-a41d-fb20c2deb50b.png)

**Comment by aheinze** [comment]
Cockpit doesn't come wit an icon pack (yet). But it loads custom icons. Create a folder named `icons` in the config folder and put there your custom icons (*.svg)

**Comment by McGonigleStudio** [comment]
> Cockpit doesn't come with an icon pack (yet). But it loads custom icons. Create a folder named `icons` in the config folder and put there your custom icons (*.svg)
> 
> Then you should be able to pick them in the icon picker.

The solution works perfectly. Thank you. 👍
