### ISSUE TITLE
how to create a custom installation of cockpit?

### ISSUE THREAD

**Issue by jbeuria** [Cockpit-HQ/Cockpit#4]
Is there a way to install cockpit-core outside the server document root? If so, how to add custom environment variables like `$APP_ROUTE`, `$APP_BASE_URL`, etc?

**Comment by aheinze** [comment]
Cockpit is built with a "plug & play" concept in mind. Just put it on a webserver and it runs. Whether it is simple shared webhosting (which has just has its root as public folder), a vps, dedicated server or cloud. It should just run without any further configuration.

I also think that having a `public` folder is more a common practice than best practice. If you've security concerns, then you just have to configure your webserver properly.

E.g. for apache add the following to `.htaccess`:

```
<Files *.php>
    Order Deny,Allow
    Deny from all
</Files>

<Files index.php>
    Order Allow,Deny
    Allow from all
</Files>
```

which won't allow any public acces to your application code except the router entry file (index.php).

**Comment by jbeuria** [comment]
> Cockpit is built with a "plug & play" concept in mind. Just put it on a webserver and it runs. Whether it is simple shared webhosting (which has just has its root as public folder), a vps, dedicated server or cloud. It should just run without any further configuration.
> 
> I also think that having a `public` folder is more a common practice than best practice. If you've security concerns, then you just have to configure your webserver properly.
> 
> E.g. for apache add the following to `.htaccess`:
> 
> ```
> <Files *.php>
>     Order Deny,Allow
>     Deny from all
> </Files>
> 
> <Files index.php>
>     Order Allow,Deny
>     Allow from all
> </Files>
> ```
> 
> which won't allow any public acces to your application code except the router entry file (index.php).

Thanks for your quick response. I shall do the same. Also, thanks a lot for creating such a nice CMS.
