### ISSUE TITLE
Can't edit User because it is being edited by myself

### ISSUE THREAD

**Issue by CapsE** [Cockpit-HQ/Cockpit#42]
While testing a different issue I noticed that if I edit my non admin user-account (or try to anyway), switch to a different account and log back in to the first my user can't be edited because it's currently being worked on by myself.

Steps to reproduce:

1. Log in as non admin "lkr"
2. edit User (doesn't work error 401)
3. log out
4. log in as admin
5. don't edit anything and just log out
6. login as "lkr" again
7. can't edit user because it's being worked on by "lkr"

**Comment by aheinze** [comment]
Fixed https://github.com/Cockpit-HQ/Cockpit/commit/c57aeb400b2e79ac1bcac369f20c23fea0a01193
