### ISSUE TITLE
Installing on cPanel

### ISSUE THREAD

**Issue by ilomon10** [Cockpit-HQ/Cockpit#45]
How do i can install this cockpit on cPanel on web hosting?

**Comment by darkylmnx** [comment]
You just need to put it at the root of your domain, wether it's `public_html` or `www`.
Then, go to your domain and on the URL `/install`.
From there, the default login and password is `admin`.

That's it. Cockpit works with sqlite so no need to setup and MySQL database or whatever.

**Comment by ilomon10** [comment]
@darkylmnx Thankyou
