### ISSUE TITLE
Is there a way to extend Cockpit? Write reusable plugins?

### ISSUE THREAD

**Issue by darkylmnx** [Cockpit-HQ/Cockpit#47]
Hi,

Is there a way to extend Cockpit to write things like:
- custom endpoints
- custom field types
- custom admin pages

For internal use or for sharing with other Cockpit users who may want some specific features?

**Comment by aheinze** [comment]
Hi,

sure! You can create your custom addon/module and implement whatever you want

**Comment by darkylmnx** [comment]
I'm sorry my question wasn't clear enough, I meant, where can I find how to do that in the docs?

I didn't see anything about that in the docs, or is the only way to do that is to check the source code ?

**Comment by erickilisboars** [comment]
I'm also trying to understand how to create new custom fields

**Comment by darkylmnx** [comment]
@aheinze any sources/guides/tutorial on how to do this?

Because I looked at the docs again, and didn't see anything.

**Comment by aheinze** [comment]
There is no documentation right, but you can just look into the available modules/addons . Shouldn't be really that hard 🙂

**Comment by darkylmnx** [comment]
I just checked out the source code of the addons in the PRO version.
It's not so easy to understand without a documentation...
At least, without spending days reading and understanding the architecture.

For example, understanding how `dataStorage` works is pretty hard.

In any case, the main thing I was looking for doesn't seem to be there.

How can we easily **filter** the response of a collection to add custom data in the response?
Do I have to necessarily override the `modules/Content/api.php` file?
Is there no "hook" system that takes the data before the response?
Something like: https://docs.directus.io/extensions/hooks.html

Also to create a custom endpoint, I understand how to register the route?
Are the files auto-discorvered in `addons/{MyCustom}/api.php` ?
What is the following for:
```php
<?php

/**
 *
 * @OA\Tag(
 *   name="content",
 *   description="Content module",
 * )
 */
```

Thanks in advance.

Usually I use a headless CMS to code the less possible, so when it becomes more
difficult to use it than creating an API myself the ROI becomes less interesting haha.

**Comment by darkylmnx** [comment]
@erickilisboars have you had more chance than me on this?

**Comment by aheinze** [comment]
a simple example:

in your `addons/{MyCustom}/bootstrap.php`:

```
$this->on('restApi.config', function($restApi) {

    $restApi->addEndPoint('/{mycustom}/whatever', [
        'GET' => function($params, $app) {
            return ['success' => true];
        }
    ]);

});
```

Now you can call `/api/mycustom/whatever`

**Comment by darkylmnx** [comment]
@aheinze  Okay, so the bootstrap file is the necessary file for the addons discovery.

But how can I filter the response of a collection to add custom data in the response?
Is there no "hook" system that takes the data before the response?
Something like: https://docs.directus.io/extensions/hooks.html

**Comment by aheinze** [comment]
in your addons/{MyCustom}/bootstrap.php:

```
$this->on('content.api.items', function(&$items, $model) {

  // do whatever you like with $items
});
´´´

**Comment by darkylmnx** [comment]
Okay thanks.

Is there a plan to have a documentation for people who buy the PRO package?

I really want to use Cockpit because it's PHP and cPanel friendly, but I need to be sure i'll have some documentation
at some point.

Is something planned for this?

**Comment by darkylmnx** [comment]
@aheinze have you seen my previous message?

**Comment by aheinze** [comment]
It's planned to publish guides to cover different scenarios.
