### ISSUE TITLE
UI: Add title label to title fields

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#48]
<img width="937" alt="Screenshot showing the top of a new Layout page" src="https://user-images.githubusercontent.com/27637/204482351-b7d4abc0-8aed-48aa-b1ac-d2cf921dc8cf.png">

In the attached screenshot from the creation of a new Layout article type, it's not obvious what the 3rd and 5th fields are for. They are for the "title" of the translations, but it's not obvious (esp. as the "Slug" label looks equidistant between it's field (below) and the field above).

I suggest adding a "Title" label above the title fields and putting a little bit more spaces between the input and the next groups label.

**Comment by aheinze** [comment]
Fixed. Will be released in 2.3.5 👍
