### ISSUE TITLE
UX: Page selectors to show page list in matching translation by default

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#49]
When you need to link to another page on a multi-language site, currently the Page selection list always initially loads in the default language.

It would be nicer if it was "translation aware"; in that the Page list translation would automatically load to match the translation of the section currently being edited.

In the attached video, a block in the English translation is being edited. When link page button is pressed, the Pages list shows German (the default language for this site). It would be nicer if the list showed English Pages [but retains the option to change the list to another locale if needed], but in most cases links between blocks and pages would likely be set to the same language by the site Editor.

https://user-images.githubusercontent.com/27637/204522011-d942538e-c205-4245-b15c-fb93522f0232.mp4

**Comment by aheinze** [comment]
Fix will be available in version > 2.3.4
