### ISSUE TITLE
Displaying ContentLink  preview in Admin Dashboard

### ISSUE THREAD

**Issue by jbeuria** [Cockpit-HQ/Cockpit#5]
@aheinze  I am trying to display one of the fields in ContentLink as it used be in older Cockpit, but no entry preview is coming! Could you help me fix it.

![image](https://user-images.githubusercontent.com/57653501/179347561-d2eccf37-3687-4d11-880f-c4f89358b377.png)

**Comment by aheinze** [comment]
try `${data.email}` in the display field

**Comment by niko-donskoy** [comment]
Thаnks
