### ISSUE TITLE
Bring back manual sorting

### ISSUE THREAD

**Issue by ebrenner-code** [Cockpit-HQ/Cockpit#52]
The ability to enable manual sorting on a collection thereby letting an editor drag and drop content was so powerful and unique to the previous version of cockpit. I would love to see it make its way back in the new version.

**Comment by aheinze** [comment]
Please choose a "tree" model type when creating a content model:

![image](https://user-images.githubusercontent.com/321047/207231827-1bce265a-9b0d-4c30-927b-f5a6376c0407.png)

**Comment by ebrenner-code** [comment]
Thank you, in that case, I would change my feature request to limit how many levels you can nest in a tree model. However, if I limit the tree model to 0 nests, is that still a tree? The tree model currently creates an opportunity for the client to shape the data in an unexpected or unwanted way and that has to be considered in fetching the data as well.

**Comment by aheinze** [comment]
>  I would change my feature request to limit how many levels you can nest in a tree model

![image](https://user-images.githubusercontent.com/321047/207335757-6271f913-d058-4073-8b6e-70a9c27b42a3.png)

PS: There is a not released yet fix if level = 0
https://github.com/Cockpit-HQ/Cockpit/commit/78d6cd56692a47ddf7447143629ba664baf12334

**Comment by ebrenner-code** [comment]
Great to see this is on your radar. If I understand correctly, if maxlevel = 0, then it acts as maxlevel = unlimited?

**Comment by aheinze** [comment]
> If I understand correctly, if maxlevel = 0, then it acts as maxlevel = unlimited?

Nope, then you can just reorder the items on the root level but can't nest them. maxlevel = false -> unlimited (default)

**Comment by ebrenner-code** [comment]
Unfortunately, that's not the experience I am having. Was this included in a very recent update? Is it possible that it's maxLevel or max_level? I don't think I need to tell you the documentation is seriously lacking.
