### ISSUE TITLE
New official Docker only supports arm64

### ISSUE THREAD

**Issue by pozylon** [Cockpit-HQ/Cockpit#53]
The image that can be found here does not work on linux amd64: https://hub.docker.com/r/cockpithq/cockpit/tags

Consider using "docker buildx" to build multi platform images.

**Comment by aheinze** [comment]
It is nothing official. Just tmp solution for those who want to try out Cockpit via docker. 
Let me know if you have any suggestions regarding automation + improvements. 

Thanks!

**Comment by aheinze** [comment]
`linux/amd64` images are also available now. Thanks for the buildx hint 👍
