### ISSUE TITLE
Children are not shown

### ISSUE THREAD

**Issue by creativecat** [Cockpit-HQ/Cockpit#55]
If you create elements in a tree and also create children, these are neither displayed in the backend nor via the API.
This seems to be a problem in 2.3.5, because everything works fine in another installation under 2.3.3.

**Comment by creativecat** [comment]
I reinstalled 2.3.4 and it was working again.
API is working fine! I see that there is a parent id, but the tag for "children" is missing.

**Comment by aheinze** [comment]
Thanks for reporting. Fix is committed and will be released soon!
