### ISSUE TITLE
Question: How to update/upgrade from Cockpit 0.12.2

### ISSUE THREAD

**Issue by patrickuhlmann** [Cockpit-HQ/Cockpit#57]
Is there any possibility to update from the last "[original](https://github.com/agentejo/cockpit/tags)" cockpit version 0.12.2? Any manual procedure?

**Comment by aheinze** [comment]
Hey 👋 Sorry for the late answer. Currently you have to do a manual migration. Maybe in the future I'll come up with a migration script.
