### ISSUE TITLE
Repeatable wysiwyg field breaks model

### ISSUE THREAD

**Issue by tsch0hnny** [Cockpit-HQ/Cockpit#58]
When adding a repeatable wysiwyg field to an existing model that already has entries, the models item overview page breaks and displays a blank page.
|  Title  |  Value  |
| ------------- | ------------- |
| Cockpit Version  | 2.3.0  |
| PHP Version  | 8.1.11 |
| PHP SAPI | litespeed |
| System | x86_64 |
| Extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, json, iconv, SPL, pcntl, readline, Reflection, session, standard, mbstring, shmop, SimpleXML, tokenizer, xml, litespeed, apcu, bcmath, dom, fileinfo, gd, gmp, imagick, imap, intl, ldap, exif, mysqlnd, mysqli, PDO, pdo_mysql, OAuth, pdo_sqlite, Phar, posix, pspell, soap, sockets, sodium, tidy, vips, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache |
| Max. execution time | 300 sec. |
| Memory limit | 256M |
| Upload file size limit | 500M |
| Realpath Cache | 4096K / 120 (ttl) |
| System temporary directory | /tmp |
| OPCache | Enabled |
| LSPHP_ENABLE_USER_INI | on |
| PHP_INI_SCAN_DIR | /etc/php_settings/conf.d |
| PATH | /usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |
| VIPSHOME | /usr |

**Comment by aheinze** [comment]
Hey 👋 Thanks for reporting. Fix is committed and will be released soon!

**Comment by tsch0hnny** [comment]
Hey @aheinze Thanks for the insanely quick fix! been loving cockpit ever since the early V1 days :D
