### ISSUE TITLE
Missing Feature for cockpit v2

### ISSUE THREAD

**Issue by creativeplus2** [Cockpit-HQ/Cockpit#6]
Hello Artur, Is there any change this below missing feature coming to cockpit v2?
1. Custom Sortable Entries for model collection ( tree + sortable )
2. Custom Icon for model collection
3. Multi select Assets like Gallery field in old cockpit? I know it can multi link assets but must one by one

Thank you for awesome work!

Christian

**Comment by aheinze** [comment]
Hi Christian 👋

1️⃣ Custom sortable will come back, not sure about the nestable content items
2️⃣ Custom icons will be available again
3️⃣ Depending on the future demand

What are your specific use cases for the nestable content items?

Greets
Artur

**Comment by jbeuria** [comment]
Also, it would be nice to have an export option and bulk import option in dashboard for collections/singletons.

**Comment by creativeplus2** [comment]
> Hi Christian 👋
> 
> 1️⃣ Custom sortable will come back, not sure about the nestable content items 2️⃣ Custom icons will be available again 3️⃣ Depending on the future demand
> 
> What are your specific use cases for the nestable content items?
> 
> Greets Artur

Thanks for the reply Artur, Most nestable content for category product, category post, etc. Its great if content link can be nestable too... so example product content can link to product category and the display the nestable product category

**Comment by aheinze** [comment]
I'll consider it, but it doesn't have the highest priority right now
