### ISSUE TITLE
Feature Request: Quick access the state.

### ISSUE THREAD

**Issue by ByteBitter** [Cockpit-HQ/Cockpit#61]
An easy way to change the state of an item. Maybe a popup that opens, when clicking on the State icon and buttons to control the state for multiple selected items.

**Comment by aheinze** [comment]
Thanks for the suggestion. Will be availble in the next release >v2.3.6

**Comment by ByteBitter** [comment]
Thanks, I pulled the current version, but unfortunately the items don't get updated. The request is send correctly and "success: true" is returned.
