### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by sgirard84** [Cockpit-HQ/Cockpit#62]
I followed the procedure to generate language files for French. I edited all the files but I can only see the translated items in very few places.

Example from the config\i18n\Content\fr.php file
This translation is fine (I can see it when I click to create a new model)
‘Tree’ => ‘Arbre’,

But this one never works, regardless of the context:
‘Content’ => ‘Contenu’,

Most translations do not seem to work. Another example. This one is supposed to translate the “Hello” message on the dashboard, but I can’t see it (edited file config\i18n\App\fr.php)
‘Hello.’ => ‘Bonjour.’,

Someone posted on forum that there is an array not set causing some problems. You can see the discussion here: 
https://discourse.getcockpit.com/t/how-to-change-the-dashboard-ui-language/2599/7

Thanks

**Comment by jmleroux** [comment]
Hello,
On my side, translations seems to work well.
And by the way, I find it would be usefull to have the translations commited in this repo so that the community can use and enrich them directly via PRs. Just my two cents.

**Comment by sgirard84** [comment]
I think we can close this issue. I found that translation is working on my web hosting but not on my local environment. I compared all the extensions and web server options, and they seem identical but there might be someting I'm missing.

**Comment by jmleroux** [comment]
FYI, I have this PR for a Docker dev env: https://github.com/Cockpit-HQ/Cockpit/pull/81

No more issues with wrong configured env with Docker :wink:
