### ISSUE TITLE
UX Suggestion: Show Lokalize key edit screen after adding a key

### ISSUE THREAD

**Issue by mountainash** [Cockpit-HQ/Cockpit#65]
When you "Add Key" in the Lokalize section, the "add" modal just disappears and in most cases you will not see the new key you've just added in a long list of keys. A better UX could be to filter the Keys to only show the newly added Key, so you can quickly add translations to it. This would improve the "common" workflow for adding Lokalize translations.

**Comment by aheinze** [comment]
Thanks for the suggestion 🙏 This is already fixed for the upcoming release
