### ISSUE TITLE
Feature: Content - Add a multi-select option to change the state (published <-> unpublished)

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#69]
**Feature: Content - Add a multi-select option to change the state (published <-> unpublished)**

On the content you can select multiple items and currently only delete them, it would be perfect if you could also change the state of all selected items quickly.

**Comment by aheinze** [comment]
Already implemented here: https://github.com/Cockpit-HQ/Cockpit/commit/33c407d7e6d4971c1a2168cf40c154623ecd9178

will be available in the next release
