### ISSUE TITLE
UI load time larger than previous version

### ISSUE THREAD

**Issue by jbeuria** [Cockpit-HQ/Cockpit#7]
Hello Arthur,

Somehow, the ui load time for v2 is little larger than earlier version. I see some assets are loaded from localhost, yet it takes as long as 5 seconds! My internet is quite good, so I don't expect a delay and subsequent fallback option to load from local resource if any.  
![image](https://user-images.githubusercontent.com/57653501/179388413-b1cd73d9-e3ad-4120-9af8-c698d50a9791.png)

**Comment by aheinze** [comment]
These numbers looks really strange. I don't get these numbers even if I enable slow 3g throttling 🤔
Looks like your webserver responds slow due to eg configuration, firewall settings or a running anti virus software intercepting http requests 🤷‍♂️

**Comment by jbeuria** [comment]
Yes, it might be the case. Will look into these aspects.
