### ISSUE TITLE
Feature: Content - Add a multi-select option to edit multiple items

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#70]
**Feature: Content - Add a multi-select option to edit multiple items**

For the old cockpit, there was an addon that had the functionality to quickly edit multiple items by selecting the fields you want to edit and it then sets the selected fields of the selected items to the specified value.

It looked like this:
![image](https://user-images.githubusercontent.com/1291358/213226223-74dc829d-e730-4b0b-9a11-443aa4ebaa9b.png)

**Comment by aheinze** [comment]
Feature just landed in current dev branch and will be available in v2.4.0
