### ISSUE TITLE
Broken adding item in tree view

### ISSUE THREAD

**Issue by srsbiz** [Cockpit-HQ/Cockpit#72]
This should not try to output result of trigger

https://github.com/Cockpit-HQ/Cockpit/blob/a8bc6ff960216184b767c31e6f5d2a033a30bb7c/modules/Content/views/tree/item.php#L129

**Comment by aheinze** [comment]
Thanks for the hint! Should be fixed now: https://github.com/Cockpit-HQ/Cockpit/commit/93ab3ac17920b0926a472ce5819ec073075d4124
