### ISSUE TITLE
Feature: Clone an item

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#74]
**Feature: Clone an item**

It would be very helpful to be able to clone an existing item to create a new item from it.

The most useful case would be when you are editing items/creating a bunch of new items and instead of "Create New Item" you can say "Clone Existing Item". Right next to this button:
![image](https://user-images.githubusercontent.com/1291358/217501522-77b67756-ad21-401b-929e-7e0a641efdef.png)

Or in the Content item overview as a new item action. Right under this action:
![image](https://user-images.githubusercontent.com/1291358/217501731-498bfde3-6f57-4061-a078-ecb81881a7b6.png)

**Comment by aheinze** [comment]
Thanks for the suggestion. Duplicating items will be available in > v2.4.1
