### ISSUE TITLE
Bug: Multi Update State does not change the State

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#75]
**Bug: Multi Update State does not change the State**

It gives an alert "State updated!", but the State of the items didn't change. I am using version 2.3.8.
I am trying to set it to Published from Unpublished. The other way around also doesn't work.

The call "content/collection/updateState" does "return success: true" with the Payload being:
`{
  "ids": [
    "63dd220b1fc6be58bb069249",
    "63dd21fb21a22842ae051df2"
  ],
  "state": 1
}`
The transmitted data are the correct _id values, but even after restarting the States are not updated.

**Comment by aheinze** [comment]
Thanks for reporting! This occurs only when using SQLite  as data storage and is fixed in the current dev branch
