### ISSUE TITLE
Bug: Min & Max values of a number are being ignored

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#76]
**Bug: Min & Max values of a number are being ignored**

The Min & Max values of a number are being ignored and you can still save the item with a "faulty" number value.
Only if you use the built-in controls with the arrow up and down the limits get respected, but if you type it in manually, you can save the item without any issues.

**Comment by aheinze** [comment]
Thanks for reporting! Fix is available in the develop branch
