### ISSUE TITLE
Feature: Accessal of fields of a "Content link" within a "Set of fields"

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#78]
**Feature: Accessal of fields of a "Content link" within a "Set of fields"**

It would be very helpful if you display fields of a "Content link" within a "Set of fields" to display a meaningful entry in the item overview. 

Currently, you can only access the "_id" Field, which results in something like this if the only meaningful entry otherwise would be a value:
![image](https://user-images.githubusercontent.com/1291358/217856157-f0c24a58-6757-42f2-bfaf-31968964ae53.png)

For example:
The content "contentA" contains the field "Name". On content "contentB" you create a "Set of fields" and a field named "Link" which is a "Content link" to "contentA".

Right now you can only choose a "Display" on "contentB" like:
${data.Link._id}

But it would be perfect if you could display fields of "contentA", otherwise the Display becomes meaningless as shown above.
Just like this for the field "Name":
${data.Link.Name}
Right now this results in a display of "Undefined".

That is a functionality that we really miss from the old version.

Thanks in advance for the response.

**Comment by aheinze** [comment]
What will be possible in >v2.3.8:

Let's assume you've a set with a field named `post` which is linked to the `posts` model, then a possible value can look like:

```
${ $content('posts', data.post._id, '${data.title}') }
```

This gets the linked posts item and displays the its `title`
