### ISSUE TITLE
Question: How do you apply a bought Pro license to a running docker installation?

### ISSUE THREAD

**Issue by Sonorpearl** [Cockpit-HQ/Cockpit#79]
**Question: How do you apply a bought Pro license to a running docker installation?**

We switched to Cockpit 2.0 from 1.0 and already tested the Pro version. Now we want to apply the already-bought License key to the running Cockpit 2.0 project. But we couldn't find any documentation on how we might do that. We are already using the image cockpithq/cockpit:pro-2.3.8.

**Comment by aheinze** [comment]
Hey 👋

First, thank you for supporting Cockpit by buying a pro license.

Regarding your question:

Currently you can't. The pro version (including docker image) comes without any limitation or notice. But this will change in the future. So keep your license key you got after the purchase 😉

**Comment by bomas13** [comment]
With a bit knowledge in PHP and reverse-engineering you can easily create your own `license.lic` file, put it in the right spot and so get rid of the "trial" notification.
