### ISSUE TITLE
Upgrade guide / migration guide coming from old cockpit

### ISSUE THREAD

**Issue by natemate90** [Cockpit-HQ/Cockpit#82]
Hi @aheinze is there somewhere an upgrade guide when coming from the legacy cockpit version? I'm currently using 0.12.2 and I'd like to know if there are any breaking changes. I'm using the following plugins:

- Detektivo
- LayoutComponents
- Moderation
- MultipleCollectionLink
- SimpleResponseCache

Best 
Nathan

**Comment by aheinze** [comment]
Hey 👋

I'm sorry to say that you'll experience a lot of breaking changes as v2.x is almost a complete rewrite. You need to migrate the data manually or eg, write a migration script to automate things.

Regarding the plugins:

- Detektivo is not ported yet to v2
- LayoutComponents is part of the Pro version now
- SimpleResponseCache is integrated into the core now
- Moderation and MultipleCollectionLink are vendor plugins, you have to ask the authors about v2
