### ISSUE TITLE
populate in GraphQL API seems broken

### ISSUE THREAD

**Issue by belafonte** [Cockpit-HQ/Cockpit#88]
Setting populate to 1 in a GraphQL query has no effect as seen in the attached image.
Whereas setting the same populate option to 1 in the REST Api properly populates all linked items. 

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/2737673/230075593-6e060073-76da-4ae8-b7cf-4c839386dc44.png">

**Comment by aheinze** [comment]
Can't verify the issue. Which Cockpit version do you use?

**Comment by belafonte** [comment]
Cockpit 2.41.

Did some digging, seems to work with Collections, but not with Singletons.

**Comment by aheinze** [comment]
Thanks for reporting, this should be fixed now in the dev branch
