### ISSUE TITLE
Old fields are not deleted from API response

### ISSUE THREAD

**Issue by axeloz** [Cockpit-HQ/Cockpit#91]
Hello, 

I created a Category field on my Post model then I removed it. 
But category still appears in the API response:

```
	"category": {
		"_model": "category",
		"_id": "6436931b4cbb71ea5f08edf7"
	},
```

Is that normal?

Thanks

**Comment by axeloz** [comment]
If I create a new Post, category does NOT appear. So if I remove a field, it is NOT removed from existed content, right?

**Comment by aheinze** [comment]
Right, this is due to the nature of document based databases. It is on my todo list to improve this. But for now you can use the CLI tools to cleanup your content items:

```
./tower content:field:remove post category     
```

this will remove all `category` keys in existing `post` items
