### ISSUE TITLE
AWS: Mass Upload & Deleting

### ISSUE THREAD

**Issue by Esylias** [Cockpit-HQ/Cockpit#96]
I'm using aws s3 integration. uploading and deleting works with single files. But i have the following issues:

1. Uploading 
Tested mass upload with 285 files, uploader responding only 20 files (checked in network tab).
Is there an limiter in config or somewhere else?

2. Deleting
File will be deleted in aws s3 but not in local storage

**Comment by aheinze** [comment]
Hey 👋

Point 1: You have to update your php.ini and adjust the `max_file_uploads` setting (default is 20)
Point 2: should be fixed in the latest release
